[2025-06-16 21:25:13,217] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: load_clean_data_ecommerce.download_data 2025-06-16T21:25:07.951724+00:00 [queued]>
[2025-06-16 21:25:13,232] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: load_clean_data_ecommerce.download_data 2025-06-16T21:25:07.951724+00:00 [queued]>
[2025-06-16 21:25:13,233] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-06-16 21:25:13,233] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2025-06-16 21:25:13,233] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-06-16 21:25:13,254] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): download_data> on 2025-06-16T21:25:07.951724+00:00
[2025-06-16 21:25:13,262] {standard_task_runner.py:52} INFO - Started process 712 to run task
[2025-06-16 21:25:13,274] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_clean_data_ecommerce', 'download_data', '2025-06-16T21:25:07.951724+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Load_data_dag.py', '--cfg-path', '/tmp/tmpc7mr1z06', '--error-file', '/tmp/tmpovyt89tx']
[2025-06-16 21:25:13,275] {standard_task_runner.py:77} INFO - Job 11: Subtask download_data
[2025-06-16 21:25:13,378] {logging_mixin.py:104} INFO - Running <TaskInstance: load_clean_data_ecommerce.download_data 2025-06-16T21:25:07.951724+00:00 [running]> on host 099b10e5e883
[2025-06-16 21:25:13,552] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_clean_data_ecommerce
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2025-06-16T21:25:07.951724+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-16T21:25:07.951724+00:00
[2025-06-16 21:25:13,569] {logging_mixin.py:104} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2025-06-16 21:25:13,587] {logging_mixin.py:104} INFO - Dataset URL: https://www.kaggle.com/datasets/carrie1/ecommerce-data
[2025-06-16 21:25:30,965] {python.py:151} INFO - Done. Returned value was: None
[2025-06-16 21:25:31,004] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=load_clean_data_ecommerce, task_id=download_data, execution_date=20250616T212507, start_date=20250616T212513, end_date=20250616T212531
[2025-06-16 21:25:31,105] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-16 21:25:31,155] {local_task_job.py:151} INFO - Task exited with return code 0
